volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: asaliev/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static
      - media:/app/media

  frontend:
    image: asaliev/kittygram_frontend
    env_file: .env
    depends_on:
      - backend  
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: asaliev/kittygram_gateway
    env_file: .env
    depends_on:
      - frontend  
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/app/media